// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoclickController from "./autoclick_controller"
application.register("autoclick", AutoclickController)

import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessagePreviewController from "./message_preview_controller"
application.register("message-preview", MessagePreviewController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import RoomListController from "./room_list_controller"
application.register("room-list", RoomListController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import UserListController from "./user_list_controller"
application.register("user-list", UserListController)
